export const LOCAL_TO_EN = {
  si: {
    'එකතු කිරීම': 'addition',
    'පසුව': 'after',
    'නැවත': 'again',
    'ගුවන්තොටුපළ': 'airport',
    'ඉඩදෙන්න': 'allow',
    'හරි': 'alright',
    'ද': 'also',
    'අප්‍රේල්': 'april',
    'වටේ': 'around',
    'ලිපිය': 'article',
    'අගෝස්තු': 'august',
    'නැන්දා': 'aunt',
    'ආයුබෝවන්': 'ayubowan',
    'බබා': 'baby',
    'නරකයි': 'bad',
    'බෑග්': 'bag',
    'බැංකුව': 'bank',
    'නාන': 'bath',
    'ලස්සනයි': 'beautiful',
    'ඇඳ': 'bed',
    'බයිසිකලය': 'bicycle',
    'කළු': 'black',
    'නිල්': 'blue',
    'බෝට්ටුව': 'boat',
    'තම්බන්න': 'boil',
    'පොත': 'book',
    'බිඳෙනවා': 'break',
    'ගෙනෙන්න': 'bring',
    'සහෝදරයා': 'bro',
    'සැලකිලිමත්': 'brother in law',
    'දුඹුරු': 'brown',
    'බස් නැවතුම': 'bus station',
    'බස්': 'bus',
    'මිලදී ගන්න': 'buy',
    'කැමරාව': 'camera',
    'හැකිය': 'can',
    'නොහැකිය': 'cant',
    'කාර්': 'car',
    'කාඩ්': 'card',
    'පරිස්සමින්': 'careful',
    'බර': 'carry',
    'බළලා': 'cat',
    'සිවිලිං විදුලි පංකාව': 'ceiling fan',
    'ජංගම දුරකථනය': 'cell phone',
    'දම්වැල': 'chain',
    'වෙනස් කරන්න': 'change',
    'දරුවා': 'child',
    'දරුවන්': 'children',
    'තේරීම': 'choice',
    'තෝරන්න': 'choose',
    'පල්ලිය': 'church',
    'පැහැදිලිව': 'clearly',
    'ක්ලික් කරන්න': 'click',
    'ඇඳුම්': 'clothing',
    'සීතල': 'cold',
    'වර්ණය': 'color',
    'එන්න': 'come',
    'පරිගණකය': 'computer',
    'සම්බන්ධ කරන්න': 'connect',
    'පිසිනවා': 'cook',
    'පිටපත් කරන්න': 'copy',
    'කැස්ස': 'cough',
    'ගණන් කරන්න': 'count',
    'ආවරණය': 'cover',
    'ගවයා': 'cow',
    'කිඹුලා': 'crocodile',
    'අඬනවා': 'cry',
    'සංස්කෘතිය': 'culture',
    'කපනවා': 'cut',
    'නටනවා': 'dance',
    'දුව': 'daughter',
    'අනිද්දා': 'day after tomorrow',
    'දවස': 'day',
    'බිහිරි': 'deaf',
    'දෙසැම්බර්': 'december',
    'ගැඹුරු': 'deep',
    'වෙනස්': 'different',
    'අමාරු': 'difficult',
    'බෙදනවා': 'divide',
    'වෛද්‍යවරයා': 'doctor',
    'ඉවරයි': 'done',
    'නොදන්නවා': 'dont know',
    'කරන්න එපා': 'dont',
    'දොර': 'door',
    'ද්විත්ව': 'double',
    'අඳිනවා': 'draw',
    'බොනවා': 'drink',
    'කනවා': 'eat',
    'දහඅට': 'eighteen',
    'අට': 'eight',
    'වැඩිමහල් සහෝදරයා': 'elder bro',
    'වැඩිමහල් සහෝදරිය': 'elder sister',
    'අලි': 'elephant',
    'එකොළහ': 'eleven',
    'ඇතුල් වෙනවා': 'enter',
    'සමාන': 'equal',
    'මකනවා': 'erase',
    'සවස': 'evening',
    'හුවමාරුව': 'exchange',
    'ඇස': 'eye',
    'ඇස්': 'eyes',
    'මුහුණ': 'face',
    'පවුල්': 'families',
    'පවුල': 'family',
    'වේගවත්': 'fast',
    'තරබාරු': 'fat',
    'පියා': 'father',
    'පෙබරවාරි': 'february',
    'හැඟීම': 'feel',
    'උණ': 'fever',
    'පහළොව': 'fifteen',
    'සටන් කරනවා': 'fight',
    'පහ': 'five',
    'මල්': 'flower',
    'අනුගමනය': 'follow',
    'කෑම': 'food',
    'හතර': 'four',
    'දහහතර': 'fourteen',
    'නිදහස්': 'free',
    'සිකුරාදා': 'friday',
    'පිරිලා': 'full',
    'නැගිටිනවා': 'get up',
    'දෙනවා': 'give',
    'යනවා': 'go',
    'රත්තරන්': 'gold',
    'සුබ සන්ධ්‍යාව': 'good evening',
    'සුබ උදෑසන': 'good morning',
    'සුබ රාත්‍රිය': 'good night',
    'හොඳයි': 'good',
    'සීයා': 'grand father',
    'ආච්චි': 'grand mother',
    'මුනුබුරා': 'grand son',
    'අළු': 'gray',
    'කොළ': 'green',
    'අළු පාට': 'grey',
    'කණ්ඩායම': 'group',
    'මගපෙන්වනවා': 'guide',
    'තුවක්කුව': 'gun',
    'එල්ලෙනවා': 'hang',
    'සතුටු': 'happy',
    'දැඩි': 'hard',
    'ටොපිය': 'hat',
    'ඔහු': 'he',
    'සෞඛ්‍ය': 'health',
    'සෞඛ්‍ය සම්පන්න': 'healthy',
    'අසනවා': 'hear',
    'හෙලෝ': 'hello',
    'උදව්': 'help',
    'මෙහි': 'here',
    'උස': 'high',
    'ගල්': 'hill',
    'පහරදෙනවා': 'hit',
    'රෝහල': 'hospital',
    'පැය': 'hour',
    'නිවස': 'house',
    'ඔබ කෙසේද': 'how are you',
    'කීයද': 'how many',
    'කොපමණද': 'how much',
    'කොහොමද': 'how',
    'සැමියා': 'husband',
    'මම දන්නවා': 'i know',
    'මම': 'i',
    'බලපෑම': 'impact',
    'තුළ': 'in',
    'නිදහස': 'independent',
    'ඇතුළත': 'inside',
    'වෙනුවට': 'instead',
    'අන්තර්ජාලය': 'internet',
    'ජනවාරි': 'january',
    'ජූලි': 'july',
    'පනිනවා': 'jump',
    'ජූනි': 'june',
    'යතුර': 'key',
    'තට්ටු කරනවා': 'knock',
    'කාන්තාව': 'lady',
    'ලැප්ටොප්': 'laptop',
    'සිනාසෙනවා': 'laugh',
    'නායකත්වය': 'lead',
    'අඩු': 'less',
    'ඉඩදෙන්න': 'let',
    'කැමතියි': 'like',
    'ලැයිස්තුව': 'list',
    'සවන්දෙනවා': 'listen',
    'ස්ථානය': 'location',
    'අගුල': 'lock',
    'බලනවා': 'look',
    'ලිහිල්': 'loose',
    'ආදරය': 'love',
    'පහත්': 'low',
    'සාදනවා': 'make',
    'මිනිසා': 'man',
    'මාර්තු': 'march',
    'මැයි': 'may',
    'හමුවෙනවා': 'meet',
    'මැද': 'middle',
    'කිරි': 'milk',
    'මනස': 'mind',
    'සඳුදා': 'monday',
    'මුදල්': 'money',
    'මාසය': 'month',
    'චන්ද්‍රයා': 'moon',
    'උදේ': 'morning',
    'අම්මා': 'mother',
    'මෝටර්සයිකලය': 'motorcycle',
    'චිත්‍රපටය': 'movie',
    'ගුණ කිරීම': 'multiplication',
    'මගේ': 'my',
    'අසල': 'near',
    'ජාලය': 'network',
    'කවදාවත්': 'never',
    'අසල්වැසි': 'next door',
    'ඊළඟ': 'next',
    'සුන්දරයි': 'nice',
    'රාත්‍රිය': 'night',
    'දහනව': 'nineteen',
    'නවය': 'nine',
    'නැත': 'no',
    'කිසිවක්': 'none',
    'හොඳ නැත': 'not good',
    'අකමැති': 'not like',
    'නොවැම්බර්': 'november',
    'දැන්': 'now',
    'ඔක්තෝබර්': 'october',
    'හරි': 'ok',
    'වයස්ගත': 'old',
    'මත': 'on',
    'එක': 'one',
    'විවෘත': 'open',
    'හෝ': 'or',
    'තැඹිලි': 'orange',
    'ඇණවුම': 'order',
    'අපේ': 'our',
    'පිටත': 'out',
    'උඩින්': 'over',
    'තීන්ත': 'paint',
    'කොටස': 'part',
    'අතීතය': 'past',
    'පාර': 'path',
    'සාමය': 'peace',
    'මුත්‍රා': 'peeing',
    'පැන්සල': 'pencil',
    'දුරකථනය': 'phone',
    'රෝස': 'pink',
    'ගුවන් යානය': 'plane',
    'සෙල්ලම්': 'play',
    'කීඩිකරු': 'player',
    'සාක්කුව': 'pocket',
    'අඟවනවා': 'point',
    'පොලිස් ස්ථානය': 'police station',
    'පොලිසිය': 'police',
    'ධනාත්මක': 'positive',
    'තෑග්ග': 'present',
    'ප්‍රශ්නය': 'problem',
    'අදිනවා': 'pull',
    'දම්': 'purple',
    'තබනවා': 'put',
    'වේගවත්': 'quick',
    'ඉක්මනින්': 'quickly',
    'විදුලි ගුවන්විදුලිය': 'radio',
    'රතු': 'red',
    'සම්බන්ධතා': 'relations',
    'පොහොසත්': 'rich',
    'මුද්ද': 'ring',
    'පාර': 'road',
    'දුවනවා': 'run',
    'සමාන': 'same',
    'වැලි': 'sand',
    'සාරි': 'saree',
    'සෙනසුරාදා': 'saturday',
    'හිරිකනවා': 'scratch',
    'සොයනවා': 'search',
    'තත්පර': 'seconds',
    'බලනවා': 'see',
    'තෝරන්න': 'select',
    'විකුණනවා': 'sell',
    'ජ්‍යෙෂ්ඨ': 'senior',
    'සැප්තැම්බර්': 'september',
    'දහහත': 'seventeen',
    'හත': 'seven',
    'ඇය': 'she',
    'කමිසය': 'shirt',
    'සාප්පුව': 'shop',
    'පෙන්වනවා': 'show',
    'සංඥා භාෂාව': 'sign language',
    'සංඥා': 'sign',
    'නැන්දම්මා': 'sister in law',
    'නංගි': 'sister',
    'වාඩිවෙනවා': 'sit',
    'දහසය': 'sixteen',
    'හය': 'six',
    'සායම': 'skirt',
    'නිදනවා': 'sleep',
    'කුඩා': 'small',
    'සිනහව': 'smile',
    'සමාජය': 'society',
    'මෘදු': 'soft',
    'පුත්‍රයා': 'son',
    'ගීතය': 'song',
    'ලේනුන්': 'squirrel',
    'නවතිනවා': 'stop',
    'වීදිය': 'street',
    'බලවත්': 'strong',
    'ව්‍යුහය': 'structure',
    'ඉගෙන ගන්න': 'study',
    'අඩු කිරීම': 'subtraction',
    'ඇඳුම': 'suit',
    'ඉරිදා': 'sunday',
    'පිසදමනවා': 'sweep',
    'පිහිනනවා': 'swim',
    'මේසය': 'table',
    'ගන්න': 'take',
    'කතාකරනවා': 'talk',
    'තේ': 'tea',
    'ඉගැන්වීම': 'teach',
    'කණ්ඩායම': 'team',
    'කඳුළු': 'tear',
    'තාක්ෂණය': 'technology',
    'දුරකථනය': 'telephone',
    'කියනවා': 'tell',
    'විහාරය': 'temple',
    'දහය': 'ten',
    'පාඨ': 'text',
    'වඩා': 'than',
    'ස්තුතියි': 'thank you',
    'ඔවුන්': 'they',
    'හොරා': 'thief',
    'සිතනවා': 'think',
    'පිපාසය': 'thirsty',
    'දහතුන': 'thirteen',
    'තුන': 'three',
    'විසිකරනවා': 'throw',
    'බ්‍රහස්පතින්දා': 'thursday',
    'ටයිට්': 'tight',
    'වේලාව': 'time',
    'ටයරය': 'tire',
    'වෙත': 'to',
    'අද': 'today',
    'හෙට': 'tomorrow',
    'දුම්රිය ස්ථානය': 'train station',
    'දුම්රිය': 'train',
    'ගස': 'tree',
    'විශ්වාසය': 'trust',
    'අඟහරුවාදා': 'tuesday',
    'දොළහ': 'twelve',
    'විස්ස': 'twenty',
    'දෙක': 'two',
    'කැත': 'ugly',
    'මාමා': 'uncle',
    'තේරුම් ගන්න': 'understand',
    'තුරු': 'until',
    'ඉහළ': 'up',
    'අපි': 'us',
    'භාවිතා කරනවා': 'use',
    'වෑන්': 'van',
    'වාහනය': 'vehicle',
    'බලන්න': 'visit',
    'ඇවිදිනවා': 'walk',
    'අවශ්‍යයි': 'want',
    'සෝදනවා': 'wash',
    'බලනවා': 'watch',
    'කාලගුණය': 'weather',
    'බදාදා': 'wednesday',
    'සතිය': 'week',
    'පිළිගන්න': 'welcome',
    'කවදාද': 'when',
    'කොහේද': 'where',
    'සුදු': 'white',
    'කවුද': 'who',
    'කාගේද': 'whom',
    'කාගේ': 'whose',
    'ඇයි': 'why',
    'බිරිඳ': 'wife',
    'ජනේලය': 'window',
    'වැඩ': 'work',
    'ලියනවා': 'write',
    'වැරදි': 'wrong',
    'අවුරුද්ද': 'year',
    'කහ': 'yellow',
    'ඔව්': 'yes',
    'ඊයේ': 'yesterday',
    'ඔබ': 'you',
    'කුඩා සහෝදරයා': 'younger bro',
    'කුඩා සහෝදරිය': 'younger sister',
  },
  ta: {
    'வணக்கம்': 'hello',
    'நீங்கள்': 'you',
    'எப்படி': 'how',
    'கூட்டல்': 'addition',
    'பிறகு': 'after',
    'மீண்டும்': 'again',
    'விமான நிலையம்': 'airport',
    'அனுமதி': 'allow',
    'சரி': 'alright',
    'மேலும்': 'also',
    'ஏப்ரல்': 'april',
    'சுற்றி': 'around',
    'கட்டுரை': 'article',
    'ஆகஸ்ட்': 'august',
    'அத்தை': 'aunt',
    'ஆயுபோவன்': 'ayubowan',
    'குழந்தை': 'baby',
    'மோசமான': 'bad',
    'பை': 'bag',
    'வங்கி': 'bank',
    'குளியல்': 'bath',
    'அழகான': 'beautiful',
    'படுக்கை': 'bed',
    'சைக்கிள்': 'bicycle',
    'கருப்பு': 'black',
    'நீலம்': 'blue',
    'படகு': 'boat',
    'கொதிக்கவை': 'boil',
    'புத்தகம்': 'book',
    'உடை': 'break',
    'கொண்டுவா': 'bring',
    'சகோ': 'bro',
    'மைத்துனர்': 'brother in law',
    'பழுப்பு': 'brown',
    'பஸ் நிறுத்தம்': 'bus station',
    'பஸ்': 'bus',
    'வாங்க': 'buy',
    'கேமரா': 'camera',
    'முடியும்': 'can',
    'முடியாது': 'cant',
    'கார்': 'car',
    'அட்டை': 'card',
    'கவனமாக': 'careful',
    'சும': 'carry',
    'பூனை': 'cat',
    'மின்விசிறி': 'ceiling fan',
    'கைபேசி': 'cell phone',
    'சங்கிலி': 'chain',
    'மாற்று': 'change',
    'குழந்தை': 'child',
    'குழந்தைகள்': 'children',
    'தேர்வு': 'choice',
    'தேர்ந்தெடு': 'choose',
    'தேவாலயம்': 'church',
    'தெளிவாக': 'clearly',
    'கிளிக்': 'click',
    'ஆடை': 'clothing',
    'குளிர்': 'cold',
    'நிறம்': 'color',
    'வா': 'come',
    'கணினி': 'computer',
    'இணை': 'connect',
    'சமை': 'cook',
    'நகல்': 'copy',
    'இருமல்': 'cough',
    'எண்ணு': 'count',
    'மூடு': 'cover',
    'பசு': 'cow',
    'முதலை': 'crocodile',
    'அழு': 'cry',
    'கலாச்சாரம்': 'culture',
    'வெட்டு': 'cut',
    'நடனம்': 'dance',
    'மகள்': 'daughter',
    'நாளை மறுநாள்': 'day after tomorrow',
    'நாள்': 'day',
    'காது கேளாத': 'deaf',
    'டிசம்பர்': 'december',
    'ஆழமான': 'deep',
    'வேறுபட்ட': 'different',
    'கடினமான': 'difficult',
    'பிரி': 'divide',
    'மருத்துவர்': 'doctor',
    'முடிந்தது': 'done',
    'தெரியாது': 'dont know',
    'வேண்டாம்': 'dont',
    'கதவு': 'door',
    'இரட்டை': 'double',
    'வரை': 'draw',
    'குடி': 'drink',
    'சாப்பிடு': 'eat',
    'பதினெட்டு': 'eighteen',
    'எட்டு': 'eight',
    'மூத்த சகோதரர்': 'elder bro',
    'மூத்த சகோதரி': 'elder sister',
    'யானை': 'elephant',
    'பதினொரு': 'eleven',
    'நுழை': 'enter',
    'சமம்': 'equal',
    'அழி': 'erase',
    'மாலை': 'evening',
    'பரிமாற்றம்': 'exchange',
    'கண்': 'eye',
    'கண்கள்': 'eyes',
    'முகம்': 'face',
    'குடும்பங்கள்': 'families',
    'குடும்பம்': 'family',
    'வேகமான': 'fast',
    'கொழுப்பு': 'fat',
    'தந்தை': 'father',
    'பிப்ரவரி': 'february',
    'உணரு': 'feel',
    'காய்ச்சல்': 'fever',
    'பதினைந்து': 'fifteen',
    'சண்டை': 'fight',
    'ஐந்து': 'five',
    'மலர்': 'flower',
    'பின்பற்று': 'follow',
    'உணவு': 'food',
    'நான்கு': 'four',
    'பதினான்கு': 'fourteen',
    'இலவசம்': 'free',
    'வெள்ளி': 'friday',
    'நிரம்பிய': 'full',
    'எழுந்திரு': 'get up',
    'கொடு': 'give',
    'போ': 'go',
    'தங்கம்': 'gold',
    'நல்ல மாலை': 'good evening',
    'நல்ல காலை': 'good morning',
    'நல்ல இரவு': 'good night',
    'நல்லது': 'good',
    'தாத்தா': 'grand father',
    'பாட்டி': 'grand mother',
    'பேரன்': 'grand son',
    'சாம்பல்': 'gray',
    'பச்சை': 'green',
    'சாம்பல் நிறம்': 'grey',
    'குழு': 'group',
    'வழிகாட்டி': 'guide',
    'துப்பாக்கி': 'gun',
    'தொங்கு': 'hang',
    'மகிழ்ச்சி': 'happy',
    'கடினமான': 'hard',
    'தொப்பி': 'hat',
    'அவன்': 'he',
    'ஆரோக்கியம்': 'health',
    'ஆரோக்கியமான': 'healthy',
    'கேள்': 'hear',
    'வணக்கம்': 'hello',
    'உதவி': 'help',
    'இங்கே': 'here',
    'உயரமான': 'high',
    'மலை': 'hill',
    'அடி': 'hit',
    'மருத்துவமனை': 'hospital',
    'மணி': 'hour',
    'வீடு': 'house',
    'நீங்கள் எப்படி இருக்கிறீர்கள்': 'how are you',
    'எத்தனை': 'how many',
    'எவ்வளவு': 'how much',
    'எப்படி': 'how',
    'கணவர்': 'husband',
    'எனக்கு தெரியும்': 'i know',
    'நான்': 'i',
    'தாக்கம்': 'impact',
    'உள்ளே': 'in',
    'சுதந்திரம்': 'independent',
    'உள்ளே': 'inside',
    'பதிலாக': 'instead',
    'இணையம்': 'internet',
    'ஜனவரி': 'january',
    'ஜூலை': 'july',
    'குதி': 'jump',
    'ஜூன்': 'june',
    'சாவி': 'key',
    'தட்டு': 'knock',
    'பெண்': 'lady',
    'மடிக்கணினி': 'laptop',
    'சிரி': 'laugh',
    'வழிநடத்து': 'lead',
    'குறைவு': 'less',
    'விடு': 'let',
    'பிடிக்கும்': 'like',
    'பட்டியல்': 'list',
    'கேள்': 'listen',
    'இடம்': 'location',
    'பூட்டு': 'lock',
    'பார்': 'look',
    'தளர்வான': 'loose',
    'காதல்': 'love',
    'குறைவு': 'low',
    'செய்': 'make',
    'ஆண்': 'man',
    'மார்ச்': 'march',
    'மே': 'may',
    'சந்தி': 'meet',
    'நடுவில்': 'middle',
    'பால்': 'milk',
    'மனம்': 'mind',
    'திங்கள்': 'monday',
    'பணம்': 'money',
    'மாதம்': 'month',
    'நிலவு': 'moon',
    'காலை': 'morning',
    'தாய்': 'mother',
    'மோட்டார் சைக்கிள்': 'motorcycle',
    'திரைப்படம்': 'movie',
    'பெருக்கல்': 'multiplication',
    'எனது': 'my',
    'அருகில்': 'near',
    'பிணையம்': 'network',
    'ஒருபோதும்': 'never',
    'அடுத்த வீடு': 'next door',
    'அடுத்து': 'next',
    'நல்லது': 'nice',
    'இரவு': 'night',
    'பத்தொன்பது': 'nineteen',
    'ஒன்பது': 'nine',
    'இல்லை': 'no',
    'எதுவும் இல்லை': 'none',
    'நல்லதல்ல': 'not good',
    'விரும்பவில்லை': 'not like',
    'நவம்பர்': 'november',
    'இப்போது': 'now',
    'அக்டோபர்': 'october',
    'சரி': 'ok',
    'பழைய': 'old',
    'மீது': 'on',
    'ஒரு': 'one',
    'திற': 'open',
    'அல்லது': 'or',
    'ஆரஞ்சு': 'orange',
    'ஆர்டர்': 'order',
    'எங்கள்': 'our',
    'வெளியே': 'out',
    'மேலே': 'over',
    'வண்ணம் பூசு': 'paint',
    'பகுதி': 'part',
    'கடந்த': 'past',
    'பாதை': 'path',
    'அமைதி': 'peace',
    'சிறுநீர்': 'peeing',
    'பென்சில்': 'pencil',
    'தொலைபேசி': 'phone',
    'பிங்க்': 'pink',
    'விமானம்': 'plane',
    'விளையாடு': 'play',
    'வீரர்': 'player',
    'பை': 'pocket',
    'சுட்டிக்காட்டு': 'point',
    'காவல் நிலையம்': 'police station',
    'காவல்துறை': 'police',
    'நேர்மறை': 'positive',
    'பரிசு': 'present',
    'பிரச்சினை': 'problem',
    'இழு': 'pull',
    'ஊதா': 'purple',
    'வை': 'put',
    'விரைவு': 'quick',
    'விரைவாக': 'quickly',
    'வானொலி': 'radio',
    'சிவப்பு': 'red',
    'உறவுகள்': 'relations',
    'பணக்கார': 'rich',
    'மோதிரம்': 'ring',
    'பாதை': 'road',
    'ஓடு': 'run',
    'ஒரே மாதிரி': 'same',
    'மணல்': 'sand',
    'புடவை': 'saree',
    'சனிக்கிழமை': 'saturday',
    'கீறு': 'scratch',
    'தேடு': 'search',
    'வினாடிகள்': 'seconds',
    'பார்': 'see',
    'தேர்ந்தெடு': 'select',
    'விற்க': 'sell',
    'மூத்தவர்': 'senior',
    'செப்டம்பர்': 'september',
    'பதினேழு': 'seventeen',
    'ஏழு': 'seven',
    'அவள்': 'she',
    'சட்டை': 'shirt',
    'கடை': 'shop',
    'காட்டு': 'show',
    'கையெழுத்து மொழி': 'sign language',
    'கையெழுத்து': 'sign',
    'மைத்துனி': 'sister in law',
    'சகோதரி': 'sister',
    'உட்கார்': 'sit',
    'பதினாறு': 'sixteen',
    'ஆறு': 'six',
    'பாவாடை': 'skirt',
    'தூங்கு': 'sleep',
    'சிறிய': 'small',
    'புன்னகை': 'smile',
    'சமூகம்': 'society',
    'மென்மையான': 'soft',
    'மகன்': 'son',
    'பாடல்': 'song',
    'அணில்': 'squirrel',
    'நிறுத்து': 'stop',
    'தெரு': 'street',
    'வலுவான': 'strong',
    'கட்டமைப்பு': 'structure',
    'படி': 'study',
    'கழித்தல்': 'subtraction',
    'உடை': 'suit',
    'ஞாயிறு': 'sunday',
    'துடை': 'sweep',
    'நீந்து': 'swim',
    'மேசை': 'table',
    'எடு': 'take',
    'பேசு': 'talk',
    'தேநீர்': 'tea',
    'கற்பி': 'teach',
    'குழு': 'team',
    'கண்ணீர்': 'tear',
    'தொழில்நுட்பம்': 'technology',
    'தொலைபேசி': 'telephone',
    'சொல்': 'tell',
    'கோவில்': 'temple',
    'பத்து': 'ten',
    'உரை': 'text',
    'விட': 'than',
    'நன்றி': 'thank you',
    'அவர்கள்': 'they',
    'திருடன்': 'thief',
    'நினை': 'think',
    'தாகம்': 'thirsty',
    'பதின்மூன்று': 'thirteen',
    'மூன்று': 'three',
    'வீசு': 'throw',
    'வியாழன்': 'thursday',
    'இறுக்கமான': 'tight',
    'நேரம்': 'time',
    'டயர்': 'tire',
    'க்கு': 'to',
    'இன்று': 'today',
    'நாளை': 'tomorrow',
    'ரயில் நிலையம்': 'train station',
    'ரயில்': 'train',
    'மரம்': 'tree',
    'நம்பிக்கை': 'trust',
    'செவ்வாய்': 'tuesday',
    'பன்னிரண்டு': 'twelve',
    'இருபது': 'twenty',
    'இரண்டு': 'two',
    'அசிங்கமான': 'ugly',
    'மாமா': 'uncle',
    'புரிந்து கொள்': 'understand',
    'வரை': 'until',
    'மேலே': 'up',
    'நாங்கள்': 'us',
    'பயன்படுத்து': 'use',
    'வேன்': 'van',
    'வாகனம்': 'vehicle',
    'பார்வையிடு': 'visit',
    'நட': 'walk',
    'வேண்டும்': 'want',
    'கழுவு': 'wash',
    'பார்': 'watch',
    'வானிலை': 'weather',
    'புதன்': 'wednesday',
    'வாரம்': 'week',
    'வரவேற்பு': 'welcome',
    'எப்போது': 'when',
    'எங்கே': 'where',
    'வெள்ளை': 'white',
    'யார்': 'who',
    'யாருக்கு': 'whom',
    'யாருடைய': 'whose',
    'ஏன்': 'why',
    'மனைவி': 'wife',
    'ஜன்னல்': 'window',
    'வேலை': 'work',
    'எழுது': 'write',
    'தவறு': 'wrong',
    'ஆண்டு': 'year',
    'மஞ்சள்': 'yellow',
    'ஆம்': 'yes',
    'நேற்று': 'yesterday',
    'நீங்கள்': 'you',
    'இளைய சகோதரர்': 'younger bro',
    'இளைய சகோதரி': 'younger sister',
  },
};